url: "https://www.apacara.com"
timezone: Asia/Jakarta
show_banner: true
show_date_schema: true

topic: "tutorial"
topic_title: "Tutorial Web"

ads:
  enabled: true
  data_ad_client: "ca-pub-3288866780282962"

baseurl: ""
permalink: /:categories/:title.html

collections_dir: tutorial
collections:
  amp:
    output: true
    permalink: /tutorial/amp/:title.html
  apa:
    output: true
    permalink: /tutorial/apa/:title.html
  html:
    output: true
    permalink: /tutorial/html/:title.html
  css:
    output: true
    permalink: /tutorial/css/:title.html
  bootstrap:
    output: true
    permalink: /tutorial/bootstrap/:title.html
  javascript:
    output: true
    permalink: /tutorial/javascript/:title.html
  mariadb:
    output: true
    permalink: /tutorial/mariadb/:title.html
  php:
    output: true
    permalink: /tutorial/php/:title.html
  cara:
    output: true
    permalink: /tutorial/cara/:title.html


bootstrap_version: "4.3.1"
bootstrap_css: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
jquery: "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
bootstrap_bundle: "https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js"
bootstrap_js: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
popper: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"

environment: "production"      # development or empty (production)
code_highlighter: ""    # prism or highlight or empty (disable) - select syntax / code hightligter

images_path:
  avatar: "/media/avatar/"
  images: "/media/"
  images_thumb: "/media/"
  favicons: "/assets/favicons/"
  logo: "/assets/logo/"

#set defult image for posts without image (absolute url eg: domain.com/myimage.png)
#if not set, local default_image will be used
default_image_url:
default_thumb_url:
image_source_link: false    #creadit link set active (clickable) if true

name: apaCara.com
short_name: apaCara
title: apaCara.com - Belajar Blogging dan Web Design
keywords: [blog,blogging,web,webdesign,webdesain]
description: "apacara.com - Belajar Apapun Dengan cara Bagaimanapun. Blogging tutorials, belajar Seputar Web Design and Development. "
description_footer: "apacara.com - Belajar Apapun Dengan cara Bagaimanapun. "

language: "id"          #your default site language

author:            #default author
  name: "Halwa RF"
  profile: "https://plus.google.com/+HalwaRF/about"
  email: apacara@yahoo.com
  avatar: "halwa.jpg"
  description: "About Halwa RF"
display_author: false

editor:
  name: "Fadlullah Fadul"
  profile: "https://plus.google.com/+FadlullahFadul/about"

publisher:
  name: "apacara.com"
  logo_url:         # if empty, use default image in logo folder
  profile: "https://plus.google.com/+HalwaRF"

facebook:
  fb_name: "@apacaracom"
  fb_app_id: "128890347793115"
  fb_admins: "100007587970981"
  profile_id: "100007587970981"
  fb_pages: "507359169629207"
  fb_url: "https://www.facebook.com/apacaracom"

twitter:
  tw_name: "@apacaracom"
  tw_username: apacaracom
  tw_url: "https://twitter.com/apacaracom"

domain_verify:                    #domain verify for validation site owner
  google: "Bb-9_R3t_YIf2hlxgbUaf__9cNRDtf423EtTwV5mxsU"
  pinterest: "268e96bba615e56c61bd247529b7a43"
  yandex: "c50334a24cd0e3e6"
  bing: "E3C6D0C7D77D3A13C3C553CAE5F409B5"

social:
  email:
  youtube: "https://www.youtube.com/halwarf"
  googleplus: "https://plus.google.com/+HalwaRF"
  flickr:
  github: "https://github.com/apacara"
  instagram:
  linkedin:
  pinterest: "https://www.pinterest.com/halwarf"
  rss:
  stackoverflow:

use_fb_comments: false            #if false, disqus comment will be used instead
disqus:                           # apacara
disqus_script_url: "https://apacara.github.io/embed/gravcms/disqus-apacara2.html"

google_analytics: "UA-92050092-5"

markdown            : kramdown
highlighter         : rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true
#markdown_ext        : "htm,html,markdown,md"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - "*.php"