# Used for Sitemap.xml and RSS feed
url: "https://www.apacara.com"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)

baseurl: ""
permalink: /blog/:title.html

images_path:
  avatar: "/media/avatar/"
  images: "/media/posts/"
  images_thumb: "/media/posts/thumbs/"
  favicons: "/media/favicons/"
  logo: "/media/logo/"

#set defult image for posts without image (absolute url eg: domain.com/myimage.png)
#if not set, local default_image will be used
default_image_url:
default_thumb_url:
image_source_link: false    #creadit link set active (clickable) if true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"  # default layout: post to every post page

# Name of your site
name: apaCara.com
title: apaCara.com - Belajar Blogging dan Web Design
keywords: [blog,blogging,web,webdesign,webdesain]
description: "apacara.com - Belajar Apapun Dengan cara Bagaimanapun. Blogging tutorials, belajar Seputar Web Design and Development. "
description_footer: "apacara.com - Belajar Apapun Dengan cara Bagaimanapun. "

language: "en"          #your default site language

author:            #default author
  name: "Halwa RF"
  profile: "https://plus.google.com/+HalwaRF/about"
  email: apacara@yahoo.com
  avatar: "halwa.jpg"
  description: "About Halwa RF"
display_author: false

editor:
  name: "Fadlullah Fadul"
  profile: "https://plus.google.com/+FadlullahFadul/about"

publisher:
  name: "apacara.com"
  logo_url:         # if empty, use default image in logo folder

facebook:
  fb_app_id: "1935119683409174"
  fb_admins: "1920367588226155"
  fb_url: "https://www.facebook.com/halwarf"

twitter:
  tw_name: "@halwarf"
  tw_username: halwarf
  tw_url: "https://www.twitter.com/halwarf"

domain_verify:                    #domain verify for validation site owner
  google: "Bb-9_R3t_YIf2hlxgbUaf__9cNRDtf423EtTwV5mxsU"
  pinterest: "b2d3e9c573a74ffea0cf126e762c002f"
  yandex: "c50334a24cd0e3e6"
  bing: "E3C6D0C7D77D3A13C3C553CAE5F409B5"

social:
  email:
  youtube: "https://www.youtube.com/halwarf"
  googleplus: "https://plus.google.com/+HalwaRF"
  flickr:
  github: "https://github.com/apacara"
  instagram:
  linkedin:
  pinterest: "https://www.pinterest.com/halwarf"
  rss:
  stackoverflow:

# Disqus shortname
disqus: apacara
disqus_script_url: "https://apacara.github.io/embed/gravcms/disqus-apacara2.html"

# Google Analytics (e.g. UA-2110908-2)
google_analytics: "UA-92050092-5"

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'monokai'

# Use the following plug-ins
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "page:num"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  my_collection:
    output: true